name: RealmAltars
version: '${project.version}'
main: me.lucyn.realmaltars.RealmAltars
api-version: 1.21

depend: [FourthRealmCore]

commands:
  realmaltars:
    usage: "/realmaltars [setaltar|setblessing] [blessingName]"
+